### ISSUE TITLE
script 内容显示

### ISSUE THREAD

**Issue by wk989898** [sbfkcel/towxml#144]
解析 html时 怎么样让`<script>`中的内容不要显示

**Comment by sbfkcel** [comment]
把这块的内容在交给 towxml 之前去掉吧。我记得 towmxl 应该也是有处理的呀。

**Comment by wk989898** [comment]
我用css解决了
```css
.h2w__script{
  display: none;
}
```
