### ISSUE TITLE
样式冲突

### ISSUE THREAD

**Issue by JQiue** [sbfkcel/towxml#267]
当小程序开启`styleIsolation: "shared"`选项时，towxml 的标签选择器样式会影响该组件的样式，建议使用别的选择器替代，以免发生样式冲突

如下：

```css
/**内置元素**/
image,video {
    max-width: 100%;
}


video {
    width:100%; margin: 10rpx auto;
}

image {
    height:auto; vertical-align:middle;
}

video {
    height:220px; font-size:0;
}
```
