### ISSUE TITLE
[bug]底部链接或者头部p标签导致留空白问题修复

### ISSUE THREAD

**Issue by yicm** [sbfkcel/towxml#89]
@sbfkcel 

**问题表现：**
![image](https://user-images.githubusercontent.com/18110379/65586939-97c83380-dfb7-11e9-9c89-c9414bef155c.png)

**解决办法，main.wxss 添加：**

```css
.h2w__p:first-child {
    margin-top: 0;
}

.h2w__p:last-child {
    margin-bottom: 0;
}

.h2w__ul:last-child {
    margin-bottom: 0;
}

.h2w__ol:last-child {
    margin-bottom: 0;
}

```
